export type Tree = {
    name: string;
    type: 'fruit' | 'deciduous' | 'conifer';
}

 const trees: Tree[] = [
    { name: 'Apple Tree', type: 'fruit' },
    { name: 'Oak Tree', type: 'deciduous' },
    { name: 'Pine Tree', type: 'conifer' },
    { name: 'Cherry Tree', type: 'fruit' },
    { name: 'Maple Tree', type: 'deciduous' },
    { name: 'Fir Tree', type: 'conifer' },
    { name: 'Orange Tree', type: 'fruit' },
    { name: 'Willow Tree', type: 'deciduous' },
    { name: 'Spruce Tree', type: 'conifer' },
    { name: 'Lemon Tree', type: 'fruit' },
    { name: 'Birch Tree', type: 'deciduous' },
    { name: 'Cedar Tree', type: 'conifer' },
    { name: 'Peach Tree', type: 'fruit' },
    { name: 'Elm Tree', type: 'deciduous' },
    { name: 'Juniper Tree', type: 'conifer' },
    { name: 'Pear Tree', type: 'fruit' },
    { name: 'Poplar Tree', type: 'deciduous' },
    { name: 'Cypress Tree', type: 'conifer' },
    { name: 'Plum Tree', type: 'fruit' },
    { name: 'Beech Tree', type: 'deciduous' },
    { name: 'Redwood Tree', type: 'conifer' },
    { name: 'Mango Tree', type: 'fruit' },
    { name: 'Sycamore Tree', type: 'deciduous' },
    { name: 'Hemlock Tree', type: 'conifer' },
    { name: 'Banana Tree', type: 'fruit' },
    { name: 'Ash Tree', type: 'deciduous' },
    { name: 'Yew Tree', type: 'conifer' },
    { name: 'Grapevine Tree', type: 'fruit' },
    { name: 'Aspen Tree', type: 'deciduous' },
    { name: 'Larch Tree', type: 'conifer' },
    { name: 'Fig Tree', type: 'fruit' },
    { name: 'Hickory Tree', type: 'deciduous' },
    { name: 'Pineapple Tree', type: 'fruit' },
    { name: 'Chestnut Tree', type: 'deciduous' },
    { name: 'Douglas Fir Tree', type: 'conifer' },
    { name: 'Kiwi Tree', type: 'fruit' },
    { name: 'Ginkgo Tree', type: 'deciduous' },
    { name: 'Norfolk Island Pine Tree', type: 'conifer' },
    { name: 'Avocado Tree', type: 'fruit' },
    { name: 'Walnut Tree', type: 'deciduous' },
    { name: 'Red Pine Tree', type: 'conifer' },
    { name: 'Pomegranate Tree', type: 'fruit' },
    { name: 'Willow Oak Tree', type: 'deciduous' },
    { name: 'Blue Spruce Tree', type: 'conifer' },
    { name: 'Papaya Tree', type: 'fruit' },
    { name: 'Sweetgum Tree', type: 'deciduous' },
    { name: 'White Cedar Tree', type: 'conifer' },
    { name: 'Persimmon Tree', type: 'fruit' },
    { name: 'Red Maple Tree', type: 'deciduous' },
    { name: 'Norway Spruce Tree', type: 'conifer' }
];

export default trees;